import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {SqliteMetadataRepository} from '../../apps/local-core/src/metadata-repository.ts';
import {createMvpSampleSnapshot} from '../../apps/local-core/src/mvp-sample-project.ts';
import {PresentationApplicationService} from '../../apps/local-core/src/presentation-application-service.ts';
import {MutationSafetyService} from '../../apps/local-core/src/mutation-safety-service.ts';
import {RailwayDestinationService} from '../../apps/local-core/src/railway-destination-service.ts';
import {RailwayReceiveService,parsePortalReceiveRequest} from '../../apps/local-core/src/railway-receive-service.ts';
import {handleF6AssemblyRoute} from '../../apps/local-core/src/routes/f6-assembly.ts';
import {handleSpatialBindingsRoute} from '../../apps/local-core/src/routes/spatial-bindings.ts';

async function fixture(){
 const dir=await mkdtemp(join(tmpdir(),'lcos-r8-')),file=join(dir,'metadata.sqlite');let db=new SqliteMetadataRepository(file);
 const sample=createMvpSampleSnapshot(join(dir,'files'),'2026-09-30T08:00:00.000Z'),p=String(sample.project.id);
 db.save({...sample,scopes:[...sample.scopes,{...sample.scopes[0]!,id:'child-scope' as never,kind:'workflow' as const}],
  workspaces:[...sample.workspaces.map((w,i)=>({...w,preferredSurface:i===0?'main':w.preferredSurface,canvasId:`root-${i}`})),
   ...['one','two'].map(n=>({...sample.workspaces[0]!,id:n as never,scopeId:'child-scope' as never,name:`现场 ${n}`,preferredSurface:'workflow',canvasId:`canvas-${n}`,focusedViewIds:[]}))]});
 const mutations=()=>new MutationSafetyService(db,new PresentationApplicationService(db as never,db));
 const service=()=>new RailwayReceiveService(db,mutations());
 const request=(extra:any={})=>({schemaVersion:1 as const,projectId:p,operationId:`portal-receive:${randomUUID()}`,viaPortal:true as const,
  destination:{kind:'worksite' as const,projectId:p,worksiteId:'one'},expectedCanvasId:'canvas-one',sourceCanvasId:'root-0',
  sourceRefs:[{kind:'artifactView' as const,id:String(sample.artifactViews[0]!.id)}],...extra});
 const route=async(method:string,pathname:string,input?:unknown)=>{let status=0,body:any;const ctx:any={method,pathname,request:{},response:{},controller:new AbortController(),url:new URL('http://core'+pathname),metadata:db,mutationSafety:mutations(),helpers:{readJsonBody:async()=>input,isRecord:(v:any)=>!!v&&typeof v==='object'&&!Array.isArray(v),sendJson:(_r:any,c:number,b:any)=>{status=c;body=b;},failure:(code:string,message:string)=>({ok:false,error:{code,message}})}};const handled=await handleF6AssemblyRoute(ctx)||await handleSpatialBindingsRoute(ctx);return {status,body,handled};};
 const claim=(node='node-portal',target='one',source='root-0',canvas='canvas-one')=>db.claimWorkspacePortalBinding(p,target,source,node,canvas);
 return {p,sample,db:()=>db,service,mutations,request,route,claim,reopen:()=>{db.close();db=new SqliteMetadataRepository(file);},cleanup:async()=>{db.close();await rm(dir,{recursive:true,force:true});}};
}
async function run(fn:(s:Awaited<ReturnType<typeof fixture>>)=>unknown){const s=await fixture();try{await fn(s);}finally{await s.cleanup();}}

test('R8 Portal: unpinned workspace receives exact view without creating navigation records',()=>run(s=>{const before=s.db().get(s.p)!;const r=s.request(),v=s.service().receivePortal(s.p,r);assert.equal(v.status,'committed');assert.equal(v.result.results[0]?.channel,'workspace-membership');assert.equal(s.db().getRailwayOrderRecord(s.p),undefined);const after=s.db().get(s.p)!;assert.deepEqual(after.artifactViews,before.artifactViews);assert.deepEqual(after.workspaces,before.workspaces);assert.equal(after.artifacts.length,before.artifacts.length);}));
test('R8 Portal: batch receipt and precise revision survive SQLite close/reopen',()=>run(s=>{const r=s.request({sourceRefs:s.sample.artifactViews.slice(0,2).map(v=>({kind:'artifactView',id:String(v.id)}))});const a=s.service().receivePortal(s.p,r);s.reopen();assert.deepEqual(s.service().receivePortal(s.p,r),a);assert.deepEqual(s.service().lookup(s.p,r.operationId,true),a);assert.equal(s.db().listWorkspaceMembers('one' as never).length,2);assert.deepEqual(s.db().getArtifactView(String(s.sample.artifactViews[0]!.id)),s.sample.artifactViews[0]);}));
test('R8 Portal: readback channel and project must match original operation',()=>run(s=>{const r=s.request();s.service().receivePortal(s.p,r);assert.equal(s.service().lookup(s.p,r.operationId),undefined);assert.equal(s.service().lookup('other',r.operationId,true),undefined);}));
test('R8 Portal: one invalid source rolls back every membership and receipt',()=>run(s=>{const r=s.request({sourceRefs:[...s.request().sourceRefs,{kind:'artifactView',id:'missing'}]});assert.throws(()=>s.service().receivePortal(s.p,r));assert.equal(s.db().listWorkspaceMembers('one' as never).length,0);assert.equal(s.db().getCurationReceipt(r.operationId),undefined);}));
test('R8 Portal: mixed view and note uses existing tables, no geometry mutation',()=>run(s=>{const before=s.db().get(s.p)!;s.service().receivePortal(s.p,s.request({sourceRefs:[...s.request().sourceRefs,{kind:'note',id:String(s.sample.notes[0]!.id)}]}));s.reopen();assert(s.db().get(s.p)!.workspaceEntityMemberships?.some(m=>m.entityId===String(s.sample.notes[0]!.id)));assert.deepEqual(s.db().get(s.p)!.artifactViews,before.artifactViews);}));
test('R8 Portal: same canvas, foreign/missing source and stale target reject',()=>run(s=>{for(const x of [{sourceCanvasId:'canvas-one'},{sourceCanvasId:'foreign'},{expectedCanvasId:'stale'},{sourceCanvasId:''}])assert.throws(()=>s.service().receivePortal(s.p,s.request(x)));assert.equal(s.db().listWorkspaceMembers('one' as never).length,0);}));
test('R8 Portal: canvas ambiguity is unavailable, not first-match navigation',()=>run(s=>{s.db().updateWorkspaceCanvasId(s.p,'two','canvas-one');const v=new RailwayDestinationService(s.db()).resolveWorkspace(s.p,'one');assert.equal(v.available,false);assert.throws(()=>s.service().receivePortal(s.p,s.request()));}));
test('R8 Portal: changed canvas cannot silently retarget existing preview or claim',()=>run(s=>{s.db().updateWorkspaceCanvasId(s.p,'one','new-canvas');assert.throws(()=>s.service().receivePortal(s.p,s.request()));assert.throws(()=>s.claim());assert.equal(s.db().getProjectionBindings(s.p).length,0);}));
test('R8 Portal: abort before commit leaves no mutations',()=>run(s=>{const c=new AbortController();c.abort();const r=s.request();assert.throws(()=>s.service().receivePortal(s.p,r,c.signal));assert.equal(s.db().getCurationReceipt(r.operationId),undefined);}));
test('R8 Portal: unsupported, duplicate or coordinate-injected sources fail as a whole',()=>run(s=>{for(const x of [{sourceRefs:[{kind:'collection',id:'set'}]},{sourceRefs:[...s.request().sourceRefs,...s.request().sourceRefs]},{x:20},{expectedOrderVersion:0},{viaPortal:false}])assert.throws(()=>s.service().receivePortal(s.p,s.request(x)));}));
test('R8 Portal: original replay does not accept a different target or content',()=>run(s=>{const r=s.request();s.service().receivePortal(s.p,r);s.reopen();assert.throws(()=>s.service().receivePortal(s.p,{...r,sourceRefs:[{kind:'note',id:String(s.sample.notes[0]!.id)}]}));assert.throws(()=>s.service().receivePortal(s.p,{...r,expectedCanvasId:'different'}));}));
test('R8 Portal: revert existing change set makes old receipt non-replayable',()=>run(s=>{const r=s.request(),v=s.service().receivePortal(s.p,r);assert(s.mutations().revert(v.result.changeSetId!).revertable);assert.equal(s.db().listWorkspaceMembers('one' as never).length,0);assert.throws(()=>s.service().lookup(s.p,r.operationId,true));assert.throws(()=>s.service().receivePortal(s.p,r));}));
test('R8 Portal: already-present membership stays a queryable truthful no-op',()=>run(s=>{s.service().receivePortal(s.p,s.request());const r=s.request(),v=s.service().receivePortal(s.p,r);assert.equal(v.result.results[0]?.channel,'already-member');assert.equal(v.result.changeSetId,undefined);s.reopen();assert.deepEqual(s.service().lookup(s.p,r.operationId,true),v);}));
test('R8 Portal binding: one saved carrier claims identity and survives restart',()=>run(s=>{const a=s.claim();s.reopen();assert.deepEqual(s.claim(),a);assert.equal(s.db().getProjectionBindings(s.p).length,1);}));
test('R8 Portal binding: competing node cannot overwrite original winner',()=>run(s=>{const original=s.claim();assert.throws(()=>s.claim('different-node'));s.reopen();assert.deepEqual(s.db().findProjectionBinding(s.p,'root-0','node','workspace','one'),original);}));
test('R8 Portal binding: carrier already bound to another entity cannot be reused',()=>run(s=>{const b={projectId:s.p,canvasId:'root-0',spatialKind:'node' as const,spatialId:'node-portal',entityType:'artifact',entityId:String(s.sample.artifacts[0]!.id)};s.db().upsertProjectionBinding(b);assert.throws(()=>s.claim());assert.deepEqual(s.db().getProjectionBindings(s.p),[b]);}));
test('R8 Portal binding: foreign source, current canvas and missing target reject',()=>run(s=>{assert.throws(()=>s.claim('n','one','foreign'));assert.throws(()=>s.claim('n','one','canvas-one'));assert.throws(()=>s.claim('n','missing'));assert.equal(s.db().getProjectionBindings(s.p).length,0);}));
test('R8 Portal HTTP: resolve, claim and original receipt routes execute production handlers',()=>run(async s=>{const base=`/projects/${s.p}`;const target=await s.route('GET',base+'/workspaces/one/portal-target');assert.equal(target.status,200);assert.equal(target.body.value.workspaceId,'one');const claim=await s.route('POST',base+'/spatial/portals/one',{canvasId:'root-0',spatialId:'node-portal',expectedCanvasId:'canvas-one'});assert.equal(claim.status,200,JSON.stringify(claim));const r=s.request();assert.equal((await s.route('POST',base+'/portal/receive',r)).status,200);s.reopen();assert.equal((await s.route('GET',base+'/portal/receive/'+encodeURIComponent(r.operationId))).status,200);assert.equal((await s.route('GET',base+'/railway/receive/'+encodeURIComponent(r.operationId))).status,404);}));
test('R8 Portal HTTP: no coordinate fields and no claimed success on malformed body',()=>run(async s=>{const p=`/projects/${s.p}/spatial/portals/one`;assert.equal((await s.route('POST',p,{canvasId:'root-0',spatialId:'x',expectedCanvasId:'canvas-one',x:5})).status,400);assert.equal((await s.route('POST',p,{canvasId:'root-0',spatialId:'x',expectedCanvasId:'missing'})).status,409);assert.equal(s.db().getProjectionBindings(s.p).length,0);}));
test('R8 Portal parser: stable normalized fields and explicit channel',()=>{const r={schemaVersion:1,projectId:'p',viaPortal:true,operationId:'portal-receive:1234567890123456',destination:{projectId:'p',worksiteId:'w',kind:'worksite'},expectedCanvasId:'b',sourceCanvasId:'a',sourceRefs:[{kind:'note',id:'n'}]};assert.deepEqual(parsePortalReceiveRequest('p',r),parsePortalReceiveRequest('p',JSON.parse(JSON.stringify(r))));assert.throws(()=>parsePortalReceiveRequest('p',{...r,operationId:'railway-receive:1234567890123456'}));});
