/** Real file revisions, SQLite, production parser/manifest/Run route. No external execution. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {SqliteMetadataRepository} from '../../apps/local-core/src/metadata-repository.ts';
import {createMvpSampleSnapshot} from '../../apps/local-core/src/mvp-sample-project.ts';
import {ContextManifestService} from '../../apps/local-core/src/context-manifest-service.ts';
import {RuntimeApplicationService} from '../../apps/local-core/src/runtime-application-service.ts';
import {RuntimeReviewService} from '../../apps/local-core/src/runtime-review-service.ts';
import {ConversationContinuationService} from '../../apps/local-core/src/conversation-continuation-service.ts';
import {ProjectEventHub} from '../../apps/local-core/src/project-events/project-event-hub.ts';
import {parseOrderedReferences} from '../../apps/local-core/src/routes/conversation-continuation.ts';
import {handleRunsRoute} from '../../apps/local-core/src/routes/runs.ts';
import {compileContextPromptV1} from '../../apps/local-core/src/context-prompt-serializer.ts';
const refs=(id:string,revisionId='r1')=>[{order:0,ref:{type:'artifact' as const,artifactId:id,revisionId}}];
async function fixture(){
 const dir=await mkdtemp(join(tmpdir(),'lcos-r9-')),dbPath=join(dir,'metadata.sqlite');let db=new SqliteMetadataRepository(dbPath);
 const original=createMvpSampleSnapshot(join(dir,'files'),'2026-09-30T00:00:00Z'),p=String(original.project.id),a=original.artifacts[0]!;
 const revision=original.artifactRevisions.find(r=>r.id===a.currentRevisionId)!,file=original.fileRecords.find(f=>f.id===revision.fileRecordId)!;
 const texts={r1:'# 历史简报\nONLY_R1：保留人的尺度。\n不要换成最新版本。',r2:'# 最新简报\nONLY_R2：强调速度。'};
 const records=[],revisions=[];for(const [id,text] of Object.entries(texts)){const path=join(dir,id+'.md');await writeFile(path,text);const hash=createHash('sha256').update(text).digest('hex');records.push({...file,id:'f-'+id,observedPath:path,observedHash:hash,size:Buffer.byteLength(text)});revisions.push({...revision,id,artifactId:a.id,fileRecordId:'f-'+id,contentHash:hash,status:id==='r1'?'superseded':'current'});}
 const graph={...original,artifacts:original.artifacts.map(x=>x.id===a.id?{...x,currentRevisionId:'r2'}:x),fileRecords:[...original.fileRecords,...records],artifactRevisions:[...original.artifactRevisions.map(r=>r.artifactId===a.id?{...r,status:'superseded'}:r),...revisions],artifactViews:[...original.artifactViews,{...original.artifactViews[0]!,id:'view-r1',artifactId:a.id,revisionId:'r1'}]};db.save(graph as never);
 const manifests=()=>new ContextManifestService(db);
 const runtime=()=>new RuntimeApplicationService(db,manifests(),{providersStatus:async()=>[]} as never,{} as never,new RuntimeReviewService(db));
 const route=async(input:unknown,path=`/projects/${p}/runs`)=>{let status=0,body:any;await handleRunsRoute({method:'POST',pathname:path,url:new URL('http://test'+path),request:{},response:{},controller:new AbortController(),metadata:db,runtimeApplication:runtime(),helpers:{isRecord:(v:any)=>v!==null&&typeof v==='object'&&!Array.isArray(v),isStringArray:(v:any)=>Array.isArray(v)&&v.every(x=>typeof x==='string'),readJsonBody:async()=>input,sendJson:(_r:any,c:number,b:any)=>{status=c;body=b;},failure:(code:string,message:string)=>({ok:false,error:{code,message}})}} as any);return{status,body};};
 return{p,id:String(a.id),dir,graph,texts,db:()=>db,manifests,runtime,route,reopen:()=>{db.close();db=new SqliteMetadataRepository(dbPath);},cleanup:async()=>{db.close();await rm(dir,{recursive:true,force:true});}};
}
async function run(fn:(s:Awaited<ReturnType<typeof fixture>>)=>unknown){const s=await fixture();try{await fn(s);}finally{await s.cleanup();}}
for(const ref of [{type:'artifact',artifactId:'a',revisionId:'r1'},{type:'view',viewId:'v'},{type:'component',componentId:'c',presentationId:'present'}])test(`R9 parser preserves existing ${ref.type} optional address`,()=>{const a=[{ref,order:2,mode:'structure'}];assert.deepEqual(parseOrderedReferences(a),{value:a});});
for(const item of [{ref:{type:'artifact',artifactId:'a',revisionId:''},order:0},{ref:{type:'view',viewId:'v',revisionId:'r1'},order:0},{ref:{type:'artifact',artifactId:'a',unexpected:'x'},order:0},{ref:{type:'artifact',artifactId:'a'},order:-1},{ref:{type:'artifact',artifactId:'a'},order:0.5},{ref:{type:'artifact',artifactId:'a'},order:0,mode:'other'}])test(`R9 malformed reference whole-request rejection ${JSON.stringify(item)}`,()=>assert('error' in parseOrderedReferences([item])));
test('R9 parser rejects duplicate order without losing either original reference',()=>assert('error' in parseOrderedReferences([{ref:{type:'view',viewId:'v1'},order:0},{ref:{type:'view',viewId:'v2'},order:0}])));
test('R9 manifest consumes exact historical bytes and excludes implicit same-Artifact Current',()=>run(async s=>{const m=await s.manifests().build(s.p as never,{orderedReferences:refs(s.id)});assert.match(m.renderedMarkdown,/ONLY_R1/);assert(!m.renderedMarkdown.includes('ONLY_R2'));assert.deepEqual(m.references.filter(r=>r.artifactId===s.id).map(r=>r.revisionId),['r1']);}));
test('R9 exact View resolves historical file instead of current Artifact revision',()=>run(async s=>{const m=await s.manifests().build(s.p as never,{orderedReferences:[{order:0,ref:{type:'view',viewId:'view-r1'}}]});assert.match(m.renderedMarkdown,/ONLY_R1/);assert(!m.renderedMarkdown.includes('ONLY_R2'));}));
test('R9 two historical/current refs retain explicit order with independent identities',()=>run(async s=>{const m=await s.manifests().build(s.p as never,{orderedReferences:[{...refs(s.id,'r1')[0]!,order:2},refs(s.id,'r2')[0]!]});assert.deepEqual(m.references.filter(r=>r.artifactId===s.id).map(r=>r.revisionId),['r2','r1']);}));
test('R9 explicit historical overrides redundant legacy current contextArtifactIds',()=>run(async s=>{const m=await s.manifests().build(s.p as never,{contextArtifactIds:[s.id],orderedReferences:refs(s.id)});assert(!m.orderedItems.some(i=>i.artifactId===s.id&&i.revisionId==='r2'));}));
test('R9 revise target metadata and target body use same requested base revision',()=>run(async s=>{const m=await s.manifests().build(s.p as never,{targetArtifactId:s.id,targetRevisionId:'r1'});assert.equal(m.target?.revisionId,'r1');assert.equal(m.orderedItems.find(i=>i.role==='target')?.revisionId,'r1');}));
for(const [name,ref] of Object.entries({missingRevision:{type:'artifact',artifactId:'A',revisionId:'missing'},missingArtifact:{type:'artifact',artifactId:'missing',revisionId:'r1'},missingView:{type:'view',viewId:'missing'},unsupported:{type:'workspace',workspaceId:'w'}}))test(`R9 invalid ${name} cannot produce misleading task input`,()=>run(async s=>{const entry={order:0,ref:{...ref,...('artifactId' in ref&&ref.artifactId==='A'?{artifactId:s.id}:{})}};await assert.rejects(()=>s.manifests().build(s.p as never,{orderedReferences:[entry as never]}));}));
test('R9 unreadable explicit revision does not become a successful [unreadable] reference',()=>run(async s=>{await rm(join(s.dir,'r1.md'));await assert.rejects(()=>s.manifests().build(s.p as never,{orderedReferences:refs(s.id)}));}));
test('R9 production Run route persists accurate ordered references AND rendered manifest across SQLite reopen',()=>run(async s=>{const r=await s.route({instruction:'只使用刚才阅读的版本',outputIntent:'analyze',orderedReferences:refs(s.id)});assert.equal(r.status,201,JSON.stringify(r.body));const run=r.body.value.review.run;s.reopen();assert.deepEqual(s.db().getRunOrderedReferences(String(run.id)),refs(s.id));const m=s.db().getContextManifest(run.contextManifestId)!;const parsed=JSON.parse(m.canonicalJson);assert(parsed.orderedItems.some((i:any)=>i.artifactId===s.id&&i.revisionId==='r1'&&i.content.includes('ONLY_R1')));assert(!parsed.orderedItems.some((i:any)=>i.artifactId===s.id&&i.revisionId==='r2'));}));
test('R9 Run route rejects invalid mixed refs before creating any Run',()=>run(async s=>{const r=await s.route({instruction:'x',outputIntent:'analyze',orderedReferences:[...refs(s.id),{ref:{type:'unknown',id:'x'},order:1}]});assert.equal(r.status,400);assert.equal(s.db().getProjectExecutionProjection(s.p).runs.length,0);}));
test('R9 production continuation resolver receives parser-preserved history with existing content validation',()=>run(async s=>{const parsed=parseOrderedReferences(refs(s.id));assert('value' in parsed);const service=new ConversationContinuationService(s.db(),new ProjectEventHub());const result=await (service as any).resolveProviderContextReferences(s.p,parsed.value);assert.equal(result.ok,true,JSON.stringify(result));assert.match(result.value[0].text,/ONLY_R1/);assert(!result.value[0].text.includes('ONLY_R2'));assert.equal(result.evidence[0].revisionId,'r1');}));
test('R9 continuation still refuses mutated file bytes for a historical revision',()=>run(async s=>{await writeFile(join(s.dir,'r1.md'),'silently changed');const service=new ConversationContinuationService(s.db(),new ProjectEventHub());const result=await (service as any).resolveProviderContextReferences(s.p,refs(s.id));assert.equal(result.ok,false);assert.equal(result.code,'context_content_stale');}));

test("R9 actual prompt serializer keeps exact historical text in compiled task input",()=>run(async s=>{const m=await s.manifests().build(s.p as never,{orderedReferences:refs(s.id)});const prompt=compileContextPromptV1({manifest:m,userTask:"只根据旧版本分析",outputIntent:"analyze"});assert.match(prompt.stablePrefix+prompt.dynamicTail,/ONLY_R1/);assert(!(prompt.stablePrefix+prompt.dynamicTail).includes("ONLY_R2"));}));

test('R9 parser rejects non-string mode even when String(mode) looks valid',()=>assert('error' in parseOrderedReferences([{order:0,ref:{type:'artifact',artifactId:'a'},mode:['full']}])));
test('R9 task manifest refuses changed-on-disk historical content using existing revision evidence',()=>run(async s=>{await writeFile(join(s.dir,'r1.md'),'CURRENT_ONLY stored under old path');await assert.rejects(()=>s.manifests().build(s.p as never,{orderedReferences:refs(s.id)}));assert.equal(s.db().getProjectExecutionProjection(s.p).runs.length,0);}));
