// Reference capture owns one trailing click, never a time slice of the canvas.
const PICK_SUPPRESS_WINDOW_MS = 400;
let trailingPick: { nodeId: string; endedAt: number } | null = null;
let suppressorInstalled = false;
let carryMenuUntil = 0;
let pendingCarryElement: Element | null = null;
const replayedCarryMenus = new WeakSet<Event>();

/** Native contextmenu may fire on button-down (Linux) or button-up (Windows).
 * Hold it for the entire gesture, not for a 500 ms slice of a potentially long drag. */
export function beginCarryContextMenu(element: Element): void {
  pendingCarryElement = element;
  carryMenuUntil = 0;
}
export function finishCarryContextMenu(show: boolean, event: Pick<PointerEvent, 'clientX' | 'clientY'>): void {
  const element = pendingCarryElement;
  pendingCarryElement = null;
  markCarryCompleted();
  if (!show || !element?.isConnected) return;
  const menu = new MouseEvent('contextmenu', { bubbles: true, cancelable: true, button: 2,
    clientX: event.clientX, clientY: event.clientY });
  replayedCarryMenus.add(menu);
  element.dispatchEvent(menu);
}

export function markCarryCompleted(): void { carryMenuUntil = Date.now() + 500; }

export function handleCarryContextMenu(event: Event): boolean {
  if (replayedCarryMenus.has(event)) return false;
  if (pendingCarryElement === null && (carryMenuUntil === 0 || Date.now() > carryMenuUntil)) return false;
  if (pendingCarryElement === null) carryMenuUntil = 0;
  event.preventDefault();
  event.stopPropagation();
  event.stopImmediatePropagation();
  return true;
}

/** Consume only the click generated by this pointer release. A new press ends
 * this claim, even if it is on the same node within the timeout. */
export function markReferencePickCompleted(nodeId: string): void {
  trailingPick = { nodeId, endedAt: Date.now() };
}
export function clearReferenceTrailingClick(): void { trailingPick = null; }

export function handleReferenceClickSuppression(event: {
  target: EventTarget | null;
  preventDefault(): void;
  stopPropagation(): void;
  stopImmediatePropagation?(): void;
  shiftKey?: boolean;
}): boolean {
  const pending = trailingPick;
  if (!pending) return false;
  if (Date.now() - pending.endedAt > PICK_SUPPRESS_WINDOW_MS) {
    trailingPick = null;
    return false;
  }
  if (event.shiftKey === true) { trailingPick = null; return false; }
  const target = event.target as Element | null;
  if (!target || typeof target.closest !== 'function') return false;
  const node = target.closest<HTMLElement>('.react-flow__node[data-id]');
  if (node?.dataset.id !== pending.nodeId) return false;
  trailingPick = null;
  event.preventDefault();
  event.stopPropagation();
  event.stopImmediatePropagation?.();
  return true;
}

/**
 * Install the document-level capture listener once (idempotent). Audit §4.4:
 * returns a dispose so the listener is tied to the host runtime lifecycle,
 * never left dangling as a module global.
 */
export function installReferenceClickSuppressor(): () => void {
  if (suppressorInstalled || typeof document === 'undefined') return () => undefined;
  suppressorInstalled = true;
  const handler = (event: Event) => {
    handleReferenceClickSuppression(event);
  };
  document.addEventListener('click', handler, { capture: true });
  document.addEventListener('pointerdown', clearReferenceTrailingClick, { capture: true });
  const contextHandler = (event: Event): void => { handleCarryContextMenu(event); };
  document.addEventListener('contextmenu', contextHandler, { capture: true });
  let disposed = false;
  return function uninstall() {
    if (disposed) return;
    disposed = true;
    document.removeEventListener('click', handler, { capture: true });
    document.removeEventListener('pointerdown', clearReferenceTrailingClick, { capture: true });
    clearReferenceTrailingClick();
    document.removeEventListener('contextmenu', contextHandler, { capture: true });
    carryMenuUntil = 0;
    pendingCarryElement = null;
    suppressorInstalled = false;
  };
}
