import assert from 'node:assert/strict';
import test from 'node:test';
import {validateCollectionMembersSnapshot,collectionPreviewMembers,collectionRemovalConfirmed} from '../src/backend/collections.ts';
import {collectionPreviewLoadable,readCollectionPreviewMedia,COLLECTION_IMAGE_PREVIEW_BYTES} from '../../../huabu/apps/web/src/lcos/nodes/collectionPreviewMedia.ts';
import type {CoreCollectionMembersSnapshot,CollectionMemberPreview} from '../src/backend/collections.ts';
const image:CollectionMemberPreview={type:'artifact',id:'a',label:'真实图片',kind:'image',availability:'available',revisionId:'r1',fileRecordId:'f1',mimeType:'image/png',byteSize:12};
const identity={id:'c',projectId:'p',title:'集合',createdAt:'t',updatedAt:'t'};
const snapshot:CoreCollectionMembersSnapshot={collection:identity,members:[{collectionId:'c',memberRef:{type:'artifact',id:'a'},relationId:'rel',addedAt:'t'}],previews:[image]};
test('R11 read: collection project and identity must match',()=>{assert.throws(()=>validateCollectionMembersSnapshot(snapshot,'q','c'));assert.throws(()=>validateCollectionMembersSnapshot(snapshot,'p','other'));});
test('R11 read: duplicate members are not silently collapsed',()=>assert.throws(()=>validateCollectionMembersSnapshot({...snapshot,members:[...snapshot.members,...snapshot.members]},'p','c')));
test('R11 read: preview missing/extra/mismatched members never passes',()=>{for(const previews of [[],[image,image],[{...image,id:'other'}]])assert.throws(()=>validateCollectionMembersSnapshot({...snapshot,previews},'p','c'));});
test('R11 read: old Core metadata shows identities without inventing previews',()=>{const {previews,...old}=snapshot;const s=validateCollectionMembersSnapshot(old,'p','c');assert.equal(collectionPreviewMembers(s)[0]!.availability,'unreadable');assert.equal(collectionPreviewMembers(s)[0]!.fileRecordId,undefined);});
test('R11 read: previews retain membership order, not downloaded image completion order',()=>{const b={...image,id:'b'},members=[...snapshot.members,{...snapshot.members[0]!,memberRef:{type:'artifact' as const,id:'b'}}];const s=validateCollectionMembersSnapshot({...snapshot,members,previews:[b,image]},'p','c');assert.deepEqual(collectionPreviewMembers(s).map(x=>x.id),['a','b']);});
for(const availability of ['missing','stale','unreadable'] as const)test(`R11 ${availability}: no network and no latest-version fallback`,async()=>{let reads=0;const client={getFileRecordContent:async()=>{reads++;return new Blob()}};assert.equal(await readCollectionPreviewMedia(client,'p',{...image,availability},new AbortController().signal),undefined);assert.equal(reads,0);});
for(const kind of ['video','pdf','presentation','audio','file'] as const)test(`R11 ${kind}: type/title cue never eagerly downloads large binary`,async()=>{let reads=0;const client={getFileRecordContent:async()=>{reads++;return new Blob()}};await readCollectionPreviewMedia(client,'p',{...image,kind},new AbortController().signal);assert.equal(reads,0);});
test('R11 image size limit and unknown size prevent eager byte reads',()=>{for(const byteSize of [undefined,-1,Infinity,COLLECTION_IMAGE_PREVIEW_BYTES+1])assert.equal(collectionPreviewLoadable({...image,byteSize}),false);});
test('R11 preview: reads exactly the snapshot file; current changes elsewhere are irrelevant',async()=>{const calls:any[]=[];const client={getFileRecordContent:async(...args:any[])=>{calls.push(args);return new Blob(['png'],{type:'image/png'})}};const value=await readCollectionPreviewMedia(client,'p',image,new AbortController().signal);assert(value instanceof Blob);assert.deepEqual(calls[0].slice(0,2),['p','f1']);});
test('R11 preview: wrong MIME is an error, not a different-kind success',async()=>{await assert.rejects(()=>readCollectionPreviewMedia({getFileRecordContent:async()=>new Blob(['wrong'],{type:'text/plain'})},'p',image,new AbortController().signal));});
test('R11 preview: bounded real text is read; empty text stays empty',async()=>{const member={...image,kind:'text' as const,mimeType:'text/plain'};const client={getFileRecordContent:async()=>new Blob(['a'.repeat(2000)],{type:'text/plain'})};assert.equal((await readCollectionPreviewMedia(client,'p',member,new AbortController().signal) as string).length,1200);assert.equal(await readCollectionPreviewMedia({getFileRecordContent:async()=>new Blob([],{type:'text/plain'})},'p',member,new AbortController().signal),'');});
test('R11 preview: aborted response cannot publish late bytes',async()=>{const c=new AbortController();const client={getFileRecordContent:async()=>{c.abort();return new Blob(['png'],{type:'image/png'})}};await assert.rejects(()=>readCollectionPreviewMedia(client,'p',image,c.signal));});
test('R11 note: only supplied read-model excerpt, no second file request',async()=>{let calls=0;const value=await readCollectionPreviewMedia({getFileRecordContent:async()=>{calls++;throw Error()}},'p',{type:'note',id:'n',label:'笔记',kind:'note',availability:'available',excerpt:'原笔记'},new AbortController().signal);assert.equal(value,'原笔记');assert.equal(calls,0);});
test('R11 removal: removed/not-member require same member and collection',()=>{const member={type:'artifact' as const,id:'a'};for(const status of ['removed','not-member'] as const){const receipt={status,collectionId:'c',memberRef:member};assert.equal(collectionRemovalConfirmed(receipt,'c',member),true);assert.equal(collectionRemovalConfirmed(receipt,'wrong',member),false);assert.equal(collectionRemovalConfirmed(receipt,'c',{...member,id:'b'}),false);}assert.equal(collectionRemovalConfirmed({...snapshot,collectionId:'c',memberRef:member,status:'applied'} as never,'c',member),false);});

// Newly discoverable Collections must not be sent to the legacy Scope apply path.
import { assemblySourceRefOf } from '../../../huabu/apps/web/src/lcos/professional/assemblySourceRef.ts';
test('R11 canonical Collection in Assembly is readable, not a falsely enabled legacy Scope apply',()=>{
 assert.equal(assemblySourceRefOf({schemaVersion:1,kind:'collection',entityRef:{type:'collection',id:'collection-real'},title:'集合',usageCount:0}),undefined);
});
