import {test} from 'node:test';
import assert from 'node:assert/strict';
import {resolvePortalAddress} from '../../../huabu/apps/web/src/lcos/navigation/portalIdentity.ts';
import {placeExistingWorkspacePortal,type PortalPlacementPorts} from '../../../huabu/apps/web/src/lcos/navigation/portalPlacement.ts';
import {DropCommitRouter} from '../../../huabu/apps/web/src/lcos/drop/dropCommitRouter.ts';
import {resolveDropIntent} from '../../../huabu/apps/web/src/lcos/drop/dropIntentResolver.ts';
import {canCommitDropRelease} from '../../../huabu/apps/web/src/lcos/drop/dropReleaseConsistency.ts';
import {resolveNodeSpeciesFromFacts} from '../src/presentation/projectedNodeDescriptor.ts';
import {HttpClient} from '../src/backend/client.ts';
import {CoreRailwayClient} from '../src/backend/railway.ts';
const ref={kind:'worksite' as const,projectId:'p',worksiteId:'w'};
const destination={key:'w',ref,role:'worksite' as const,label:'原目标',available:true,workspaceId:'w',canvasId:'target',surface:'workflow' as const,accepts:['artifactView','note'] as const};
const payload={kind:'object' as const,entityType:'artifact',entityId:'a',artifactViewId:'historic-view'};
const target={targetId:'portal:n',kind:'portal-receive' as const,enabled:true,label:'入口',priority:25,rect:{left:100,top:100,width:200,height:200},
 semantic:{kind:'portal-receive' as const,targetRef:{kind:'workspace' as const,id:'w'},destinationRef:ref,canvasId:'target'}};
const intent={kind:'assembly-apply' as const,targetId:target.targetId,targetRef:target.semantic.targetRef,sourceRefs:[{kind:'artifactView' as const,id:'historic-view'}],portalReceive:true,railwayDestinationRef:ref,railwayCanvasId:'target'};
const outcome=()=>({status:'committed' as const,operationId:'portal-receive:1234567890123456',destination,spatial:{status:'not_required' as const},result:{schemaVersion:1 as const,projectId:'p',allApplied:true,results:[{sourceRef:intent.sourceRefs[0]!,status:'applied' as const,channel:'workspace-membership' as const}]}});
const forbidden=async()=>{throw Error('old per-item Assembly must not run');};

test('R8 identity: unique address requires real project, workspace and supported surface',()=>{const ws=[{id:'w',name:'原目标',canvasId:'target',preferredSurface:'workflow'}];assert.equal(resolvePortalAddress('p',ws,'target','w')?.workspaceId,'w');assert.equal(resolvePortalAddress(undefined,ws,'target'),undefined);assert.equal(resolvePortalAddress('p',ws,'target','other'),undefined);assert.equal(resolvePortalAddress('p',[...ws,{...ws[0]!,id:'other'}],'target'),undefined);assert.equal(resolvePortalAddress('p',[{...ws[0]!,preferredSurface:'unknown'}],'target'),undefined);});
test('R8 identity: canvas reuse never switches a pinned workspace',()=>{assert.equal(resolvePortalAddress('p',[{id:'new',name:'另一个',canvasId:'target',preferredSurface:'context'}],'target','w'),undefined);});
test('R8 renderer: native supported spacePreview reaches Portal, ordinary nodes stay native',()=>{assert.equal(resolveNodeSpeciesFromFacts({huabuNodeType:'spacePreview'}),'portal');assert.equal(resolveNodeSpeciesFromFacts({entityType:'workspace',huabuNodeType:'spacePreview'}),'portal');assert.equal(resolveNodeSpeciesFromFacts({huabuNodeType:'text'}),'unknown');});
test('R8 resolver: exact historic view uses atomic Portal intent without Railway order',()=>{const r=resolveDropIntent(payload,target);assert.equal(r.status,'ready');if(r.status==='ready'){assert.deepEqual(r.intent,intent);assert.equal((r.intent as any).railwayOrderVersion,undefined);}});
test('R8 resolver: missing canonical target is not old Assembly fallback',()=>{assert.equal(resolveDropIntent(payload,{...target,semantic:{kind:'portal-receive',targetRef:target.semantic.targetRef}}).status,'ineligible');assert.equal(resolveDropIntent(payload,{...target,semantic:{...target.semantic,destinationRef:{...ref,worksiteId:'other'}}}).status,'ineligible');});
test('R8 resolver: mixed unsupported multi-selection is rejected, not partial sent',()=>{assert.equal(resolveDropIntent({kind:'objects',objects:[payload,{entityType:'collection',entityId:'c'}]} as any,target).status,'ineligible');const r=resolveDropIntent({kind:'objects',objects:[payload,{entityType:'note',entityId:'n'}]} as any,target);assert.equal(r.status,'ready');if(r.status==='ready')assert.equal((r.intent as any).sourceRefs.length,2);});
test('R8 release: last shown target/canvas/channel must be unchanged',()=>{const state={status:'preview',destination:{targetId:target.targetId}} as any;const before={state,resolution:{status:'ready',intent}} as any;for(const patch of [{railwayCanvasId:'new'},{portalReceive:false},{railwayDestinationRef:{...ref,worksiteId:'new'}}])assert.equal(canCommitDropRelease(before,{state,resolution:{status:'ready',intent:{...intent,...patch}}}),false);assert.equal(canCommitDropRelease(before,before),true);});
test('R8 router: one gesture commits only once through the Portal transaction',async()=>{let calls=0;const owners={applyAssembly:forbidden,addComposerReference:()=>{},receivePortal:async()=>{calls++;return outcome();}};const router=new DropCommitRouter();assert.equal((await router.commit(intent,'1234567890123456',owners)).status,'success');await router.commit(intent,'1234567890123456',owners);assert.equal(calls,1);});
test('R8 router: no Portal owner never falls back to another mutation path',async()=>{const r=await new DropCommitRouter().commit(intent,'1234567890123456',{applyAssembly:forbidden,addComposerReference:()=>{}});assert.equal(r.status,'failed');});
for(const changed of ['operation','workspace','canvas','project'] as const)test(`R8 router: ${changed} mismatch is not success`,async()=>{const value=structuredClone(outcome());if(changed==='operation')value.operationId='other';if(changed==='workspace')value.destination.ref.worksiteId='other';if(changed==='canvas')value.destination.canvasId='other';if(changed==='project')value.result.projectId='other';const r=await new DropCommitRouter().commit(intent,'1234567890123456',{applyAssembly:forbidden,addComposerReference:()=>{},receivePortal:async()=>value});assert.equal(r.status,'failed');assert.equal(r.railwayOperationId,'portal-receive:1234567890123456');assert.equal(r.retrySourceRefs,undefined);});
test('R8 router: abort before release/commit does not invoke owner',async()=>{let calls=0;const c=new AbortController();c.abort();const r=await new DropCommitRouter().commit(intent,'1234567890123456',{applyAssembly:forbidden,addComposerReference:()=>{},receivePortal:async()=>{calls++;return outcome();}},c.signal);assert.equal(calls,0);assert.equal(r.status,'failed');});
test('R8 client: explicit Portal routes and conditional claim, encoded identities',async()=>{const calls:any[]=[];const client=new CoreRailwayClient(new HttpClient({baseUrl:'http://core',fetch:async(url,init)=>{calls.push({url:String(url),init});return new Response(JSON.stringify({ok:true,value:outcome()}),{headers:{'Content-Type':'application/json'}});}}));await client.portalTarget('p /','w /');await client.receivePortal({schemaVersion:1,projectId:'p',operationId:outcome().operationId,viaPortal:true,destination:ref,expectedCanvasId:'target',sourceCanvasId:'source',sourceRefs:intent.sourceRefs});await client.portalReceipt('p',outcome().operationId);await client.claimPortal('p','w','source','node','target');assert.match(calls[0].url,/p%20%2F\/workspaces\/w%20%2F\/portal-target$/);assert.match(calls[1].url,/\/portal\/receive$/);assert.equal(JSON.parse(calls[1].init.body).expectedOrderVersion,undefined);assert.match(calls[2].url,/portal-receive%3A/);assert.deepEqual(JSON.parse(calls[3].init.body),{canvasId:'source',spatialId:'node',expectedCanvasId:'target'});});
function placementFixture(){let current=true;let nodes:any[]=[];let bindings:any[]=[];let creates=0,saves=0,claims=0;const ports:{-readonly [K in keyof PortalPlacementPorts]:PortalPlacementPorts[K]}={current:()=>current,nodes:()=>nodes,bindings:async()=>bindings,readTarget:async()=>destination,create:(canvas,label)=>{creates++;nodes.push({id:'new-node',type:'spacePreview',data:{targetCanvasId:canvas,label}});return'new-node';},save:async()=>{saves++;return true;},claim:async(w,id)=>{claims++;const b={canvasId:'source',spatialId:id,entityType:'workspace',entityId:w,spatialKind:'node'};bindings=[b];return b;}};return {ports,counts:()=>({creates,saves,claims}),setCurrent:(v:boolean)=>{current=v;},setNodes:(v:any[])=>{nodes=v;},setBindings:(v:any[])=>{bindings=v;},getNodes:()=>nodes};}
const place=(s:ReturnType<typeof placementFixture>,signal?:AbortSignal)=>placeExistingWorkspacePortal('p','source',destination,s.ports,signal);
test('R8 placement: native save precedes identity claim; retry reuses same carrier',async()=>{const s=placementFixture();const a=await place(s);assert.equal(a.status,'placed');const b=await place(s);assert.equal(b.status,'existing');assert.deepEqual(s.counts(),{creates:1,saves:1,claims:1});});
test('R8 placement: cancellation during read creates nothing',async()=>{const s=placementFixture(),c=new AbortController();s.ports.readTarget=async()=>{c.abort();return destination;};await assert.rejects(place(s,c.signal));assert.equal(s.counts().creates,0);});
test('R8 placement: source switch before write creates nothing',async()=>{const s=placementFixture();s.setCurrent(false);await assert.rejects(place(s));assert.equal(s.counts().creates,0);});
test('R8 placement: stale target does not create carrier',async()=>{const s=placementFixture();s.ports.readTarget=async()=>({...destination,canvasId:'new'});await assert.rejects(place(s));assert.equal(s.counts().creates,0);});
test('R8 placement: unconfirmed save retains node and retry does not duplicate',async()=>{const s=placementFixture();const good=s.ports.save;s.ports.save=async()=>false;await assert.rejects(place(s),/保存尚未确认/);assert.equal(s.getNodes().length,1);assert.equal(s.counts().claims,0);s.ports.save=good;await place(s);assert.equal(s.counts().creates,1);});
test('R8 placement: node retargeted during save never gains stale binding',async()=>{const s=placementFixture();s.ports.save=async()=>{s.getNodes()[0].data.targetCanvasId='other';return true;};await assert.rejects(place(s));assert.equal(s.counts().claims,0);});
test('R8 placement: post-save source switch does not bind or place again',async()=>{const s=placementFixture();s.ports.save=async()=>{s.setCurrent(false);return true;};await assert.rejects(place(s));assert.equal(s.counts().claims,0);assert.equal(s.counts().creates,1);});
test('R8 placement: lost claim response is only read back, not resent',async()=>{const s=placementFixture();const claim=s.ports.claim;s.ports.claim=async(...a)=>{await claim(...a);throw Error('lost reply');};assert.equal((await place(s)).status,'placed');assert.equal(s.counts().claims,1);});
test('R8 placement: competing binding preserves both objects without overwrite/delete',async()=>{const s=placementFixture();s.ports.claim=async()=>{s.setBindings([{canvasId:'source',spatialId:'winner',spatialKind:'node',entityType:'workspace',entityId:'w'}]);throw Error('conflict');};await assert.rejects(place(s),/conflict/);assert.equal(s.getNodes().length,1);});
test('R8 placement: pre-existing missing/stale carrier is not stolen',async()=>{const s=placementFixture();s.setBindings([{canvasId:'source',spatialId:'missing',spatialKind:'node',entityType:'workspace',entityId:'w'}]);await assert.rejects(place(s),/原入口/);assert.equal(s.counts().creates,0);});
test('R8 placement: multiple unbound candidates and locked candidate need explicit user correction',async()=>{const s=placementFixture(),n={id:'n',type:'spacePreview',data:{targetCanvasId:'target'}};s.setNodes([n,{...n,id:'n2'}]);await assert.rejects(place(s),/多个/);s.setNodes([{...n,data:{...n.data,locked:true}}]);await assert.rejects(place(s),/锁定/);assert.equal(s.counts().creates,0);});

import {readProfessionalWindowLayout,writeProfessionalWindowLayout} from '../../../huabu/apps/web/src/lcos/professional/professionalWindowPersistence.ts';
import {createWindowRegion} from '../../../huabu/apps/web/src/lcos/shell/windowRegionTopology.ts';
test('R8 restore: Portal exact workspace and source node survive window serialization',()=>{const saved=Object.getOwnPropertyDescriptor(globalThis,'localStorage');const memory=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{setItem:(k:string,v:string)=>memory.set(k,v),getItem:(k:string)=>memory.get(k)??null}});try{const win={id:'p-window',bodyKey:'portal-preview' as const,title:'入口',targetKind:'canvas' as const,target:'target',portalWorkspaceId:'w',portalSourceNodeId:'n',active:true};writeProfessionalWindowLayout('p',[win],[createWindowRegion('region',[win.id],win.id)]);const restored=readProfessionalWindowLayout('p');assert.equal(restored?.windows[0]?.portalWorkspaceId,'w');assert.equal(restored?.windows[0]?.portalSourceNodeId,'n');assert.equal(readProfessionalWindowLayout('other'),undefined);}finally{if(saved)Object.defineProperty(globalThis,'localStorage',saved);else Reflect.deleteProperty(globalThis,'localStorage');}});
test('R8 restore: malformed workspace identity is not interpreted as a canvas target',()=>{const saved=Object.getOwnPropertyDescriptor(globalThis,'localStorage');const memory=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{setItem:(k:string,v:string)=>memory.set(k,v),getItem:(k:string)=>memory.get(k)??null}});try{const win={id:'p-window',bodyKey:'portal-preview',title:'入口',targetKind:'canvas',target:'target',portalWorkspaceId:2,active:true};writeProfessionalWindowLayout('p',[win as any],[createWindowRegion('region',['p-window'],'p-window')]);assert.equal(readProfessionalWindowLayout('p'),undefined);}finally{if(saved)Object.defineProperty(globalThis,'localStorage',saved);else Reflect.deleteProperty(globalThis,'localStorage');}});


test('Portal initial narrow layout reserves the second footer row without hiding actions', async () => {
  const { deriveProfessionalStageRegionPlacementsV1 } = await import('../../../huabu/apps/web/src/lcos/professional/professionalWindowStageLayout.js');
  const region = { regionId: 'portal', bodyKey: 'portal-preview', layout: 'floating' as const, preferredWidth: 472 };
  const desktop = deriveProfessionalStageRegionPlacementsV1({ viewport: { x: 0, y: 0, width: 1440, height: 900 }, regions: [region] });
  const narrow = deriveProfessionalStageRegionPlacementsV1({ viewport: { x: 0, y: 0, width: 390, height: 844 }, regions: [region] });
  assert.equal(desktop[0]?.rect.height, 496);
  assert.equal(narrow[0]?.rect.height, 536);
  assert.ok(narrow[0]!.rect.x + narrow[0]!.rect.width <= 390);
  const resized = deriveProfessionalStageRegionPlacementsV1({ viewport: { x: 0, y: 0, width: 390, height: 844 }, regions: [{...region, rect: {x: 12, y: 77, width: 366, height: 350}}] });
  assert.equal(resized[0]?.rect.height, 350, 'An explicit user-sized window is never enlarged by the initial preset');
});
