import assert from 'node:assert/strict';
import test from 'node:test';
import { createReferenceControllerState, toggleReference, removeReference, sameEntityRef, sameDraftReference, draftReferenceKey } from '../src/interaction/referenceController.js';
import { snapshotDraftReference } from '../../../huabu/apps/web/src/lcos/composer/referenceSnapshot.js';
import { composerInputKey, restoredComposerCaret } from '../../../huabu/apps/web/src/lcos/composer/composerInputJourney.js';
import { composerHasVisibleWindowOwner, assemblyBorrowsComposer } from '../../../huabu/apps/web/src/lcos/composer/composerPresentationOwner.js';
import { buildSelectedContextReferences, toRunReference } from '../../../huabu/apps/web/src/lcos/professional/conversationContinuationActions.js';
import { assemblyDraftReferenceOf } from '../../../huabu/apps/web/src/lcos/professional/assemblySourceRef.js';
import { writeProfessionalWindowLayout, readProfessionalWindowLayout } from '../../../huabu/apps/web/src/lcos/professional/professionalWindowPersistence.js';
import { createWindowRegion } from '../../../huabu/apps/web/src/lcos/shell/windowRegionTopology.js';
import type { EntityRefLike } from '../src/interaction/referenceController.js';
import type { WarehouseItemV1 } from '@local-creative-os/contracts';
const a = (revisionId?: string): EntityRefLike => ({ entityType:'artifact', entityId:'a', ...(revisionId ? {revisionId} : {}) });
const target = {nodeId:'glyth-1',title:'原会话',anchor:{x:30,y:40,width:70,height:70},intent:'continue' as const,receiverConversationId:'c1',workspaceId:'w1',messageId:'original-message'};
const item = (extra: Partial<WarehouseItemV1> = {}): WarehouseItemV1 => ({schemaVersion:1,kind:'artifact',entityRef:{type:'artifact',id:'a',viewId:'v1'},presentedRevisionId:'r1',title:'简报',usageCount:0,...extra} as WarehouseItemV1);
test('R9 canonical entity equality remains type/id, draft equality retains revision',()=>{assert(sameEntityRef(a('r1'),a('r2')));assert(!sameDraftReference(a('r1'),a('r2')));});
test('R9 two historical revisions remain ordered, removing one never removes the other',()=>{let s=createReferenceControllerState<EntityRefLike>('d');s=toggleReference(s,a('r1'));s=toggleReference(s,a('r2'));assert.deepEqual(s.orderedEntityRefs.map(r=>r.revisionId),['r1','r2']);s=removeReference(s,a('r1'));assert.deepEqual(s.orderedEntityRefs,[a('r2')]);});
test('R9 same exact revision toggles only itself',()=>{let s=createReferenceControllerState<EntityRefLike>('d');s=toggleReference(s,a('r1'));s=toggleReference(s,a('r1'));assert.equal(s.orderedEntityRefs.length,0);});
test('R9 view alias and artifact with known exact revision share draft identity',()=>{const v={entityType:'artifactView',entityId:'v1',artifactId:'a',revisionId:'r1'};assert(sameDraftReference(v,a('r1')));});
test('R9 view and artifactView spelling share identity',()=>{assert(sameDraftReference({entityType:'view',entityId:'v'},{entityType:'artifactView',entityId:'v'}));});
test('R9 unqualified current reference is not a historical reference',()=>assert(!sameDraftReference(a(),a('r1'))));
test('R9 identity keys do not collide on punctuation in ids',()=>assert.notEqual(draftReferenceKey({entityType:'a:b',entityId:'c'}),draftReferenceKey({entityType:'a',entityId:'b:c'})));
test('R9 snapshot uses the actually presented revision before Current',()=>{const r=snapshotDraftReference({...a(),descriptor:{entityType:'artifact',entityId:'a',presentedRevisionId:'r1',currentRevisionId:'r2',artifactViewId:'v1'}});assert.equal(r.revisionId,'r1');});
test('R9 projection refresh cannot alter a captured draft version',()=>{const descriptor={entityType:'artifact',entityId:'a',presentedRevisionId:'r1',currentRevisionId:'r2'};const ref=snapshotDraftReference({...a(),descriptor});descriptor.presentedRevisionId='r3';assert.equal(ref.revisionId,'r1');});
test('R9 explicit revision overrides later descriptor',()=>assert.equal(snapshotDraftReference({...a('r1'),descriptor:{entityType:'artifact',entityId:'a',presentedRevisionId:'r2'}}).revisionId,'r1'));
test('R9 mismatched descriptor cannot supply another entity version',()=>assert.equal(snapshotDraftReference({...a(),descriptor:{entityType:'artifact',entityId:'b',presentedRevisionId:'r2'}}).revisionId,undefined));
test('R9 continuation/run conversion preserves exact revision and mode',()=>{assert.deepEqual(buildSelectedContextReferences([{...a('r1'),mode:'summary'},a('r2')]).orderedReferences,[{order:0,mode:'summary',ref:{type:'artifact',artifactId:'a',revisionId:'r1'}},{order:1,ref:{type:'artifact',artifactId:'a',revisionId:'r2'}}]);});
test('R9 component presentation selector survives draft conversion',()=>assert.deepEqual(toRunReference({entityType:'component',entityId:'x',presentationId:'p'}),{type:'component',componentId:'x',presentationId:'p'}));
test('R9 unsupported note is not silently translated into an artifact',()=>{const r=buildSelectedContextReferences([a('r1'),{entityType:'note',entityId:'n'}]);assert.deepEqual(r.unsupportedEntityTypes,['note']);assert.equal(r.orderedReferences.length,1);});
test('R9 known view version becomes an exact artifact reference for the provider',()=>assert.deepEqual(toRunReference({entityType:'view',entityId:'v',artifactId:'a',revisionId:'r1'}),{type:'artifact',artifactId:'a',revisionId:'r1'}));
test('R9 warehouse reference preserves revision without materializing another object',()=>{const ref=assemblyDraftReferenceOf(item());assert.equal(ref?.revisionId,'r1');assert.equal(ref?.artifactViewId,'v1');assert.equal(ref?.entityId,'a');});
test('R9 warehouse view with no available revision keeps exact view address',()=>assert.equal(assemblyDraftReferenceOf(item({presentedRevisionId:undefined}))?.entityType,'artifactView'));
test('R9 bare artifact metadata without view or revision does not fake a reference',()=>assert.equal(assemblyDraftReferenceOf(item({presentedRevisionId:undefined,entityRef:{type:'artifact',id:'a'}})),undefined));
for(const kind of ['note','conversation','resource','workflow','context','collection'] as const)test(`R9 ${kind} retains distinct adoption route instead of guessed current-input address`,()=>assert.equal(assemblyDraftReferenceOf(item({kind,entityRef:{type:kind,id:'other'}})),undefined));
test('R9 current input key ignores visual anchor but not receiver or intent',()=>{assert.equal(composerInputKey(target),composerInputKey({...target,anchor:{x:0,y:0,width:1,height:1}}));assert.notEqual(composerInputKey(target),composerInputKey({...target,intent:'delegate'}));assert.notEqual(composerInputKey(target),composerInputKey({...target,receiverConversationId:'c2'}));});
test('R9 caret restores only for same text/task/project',()=>{const saved={projectId:'p',targetKey:'key',text:'abcdef',start:2,end:4};assert.deepEqual(restoredComposerCaret(saved,'p','key','abcdef'),{start:2,end:4});assert.deepEqual(restoredComposerCaret(saved,'q','key','abcdef'),{start:6,end:6});assert.deepEqual(restoredComposerCaret(saved,'p','other','abcdef'),{start:6,end:6});assert.deepEqual(restoredComposerCaret(saved,'p','key','new'),{start:3,end:3});});
test('R9 visible borrowed Assembly owns Composer without rewriting its target',()=>{const windows=[{id:'assembly',bodyKey:'assembly' as const,title:'取材',composerOriginKey:composerInputKey(target),active:true}];assert(assemblyBorrowsComposer(target,windows,['assembly']));assert(composerHasVisibleWindowOwner(target,windows,['assembly']));assert(!assemblyBorrowsComposer(target,windows,[]));assert(!assemblyBorrowsComposer({...target,receiverConversationId:'c2'},windows,['assembly']));assert.equal(target.messageId,'original-message');});
test('R9 material/read detour does not persist a stale input target on restart',()=>{const old=Object.getOwnPropertyDescriptor(globalThis,'localStorage');const memory=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(k:string)=>memory.get(k),setItem:(k:string,v:string)=>memory.set(k,v)}});try{writeProfessionalWindowLayout('p',[{id:'reader',bodyKey:'reader',title:'简报',target:'a',readerRevisionId:'r1',composerOriginKey:'ephemeral-target',active:true}],[createWindowRegion('r',['reader'],'reader')]);assert(![...memory.values()][0]!.includes('ephemeral-target'));assert.equal(readProfessionalWindowLayout('p')?.windows[0]?.readerRevisionId,'r1');}finally{if(old)Object.defineProperty(globalThis,'localStorage',old);else Reflect.deleteProperty(globalThis,'localStorage');}});

test('current continuation restricts picker to artifact-backed context without narrowing general Run references', async () => {
  const { draftReferenceUnavailableReason } = await import('../../../huabu/apps/web/src/lcos/composer/referenceSnapshot.ts');
  assert.equal(draftReferenceUnavailableReason({ entityType: 'artifact', entityId: 'a', revisionId: 'r1' }, 'continue'), undefined);
  assert.equal(draftReferenceUnavailableReason({ entityType: 'view', entityId: 'v1' }, 'continue'), undefined);
  assert.match(draftReferenceUnavailableReason({ entityType: 'workspace', entityId: 'w1' }, 'continue')!, /续聊/);
  assert.equal(draftReferenceUnavailableReason({ entityType: 'workspace', entityId: 'w1' }, 'delegate'), undefined);
  assert.match(draftReferenceUnavailableReason({ entityType: 'note', entityId: 'n1' }, 'delegate')!, /暂不能/);
});
